baseURL = "https://csmertx.github.io"
title = "C.S. Notes"
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"

[params]
geekdocLogo = "csmertx.jpg"
#http://flagmypicture.com/
#geekdocToC = 3
#geekdocMenuBundle = true
geekdocBreadcrumb = false
