baseURL = "https://csmertx.github.io"
title = "Chris Schammert"
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = false

# Google indexing verification (.html)
relativeUrls = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"

[params]
geekdocLogo = "crs_256x256_silver.png"
#http://flagmypicture.com/
#geekdocToC = 3
#geekdocMenuBundle = true
#geekdocBreadcrumb = true
